---
title: "01_alpha_taxa"
output: html_document
date: "2025-10-31"
---

# Load packages
```{r}
library(mia)
library(dplyr)
library(tibble)
library(tidyr)
library(purrr)
library(survival)
library(survminer)
library(writexl)
library(table1)
library(randomForestSRC)
library(ggplot2)
library(ggthemes)
library(forestploter)
library(grid)
library(patchwork)
```



```{r}
# Read tse data

tse <- readRDS("/media/project_2013220/TSE-objects/TSE_updated/tse_greengenes2_MGS.rds")


#Define covariates 
covs_nicenames <- 
      c(BL_AGE            = "Age",                
        MEN               = "Men",                
        BMI               = "BMI",
        CURR_SMOKE        = "Smoking",            
        ALKI2_FR02        = "Alcohol",                 
        Q57X              = "Physical activity",  
        PREVAL_DIAB       = "Diabetes",           
        PREVAL_CVD        = "CVD",                
        PREVAL_CR_ANYCANC = "Cancer")            
              
    covs_names <- names(covs_nicenames)
    covs_formula <- paste(covs_names, collapse = " + ")
    
# Change colData to data frame and filter by removing pregnant women, low reads, and NAs covars.

col_data <- as.data.frame(colData(tse)) 
col_data_filtered <- col_data %>% filter(PROJECT == "FR02") 
col_data_filtered <- col_data_filtered %>% filter((GRAVID == 1 | is.na(GRAVID)) & 
                                                    (total_reads > 50000) & 
                                                    (BL_USE_RX_J01_1mo == 0) & 
                                                    (PREVAL_M13_RHEUMA == 0) & 
                                                    (PREVAL_SCTD == 0) & 
                                                    (PREVAL_M13_ANKYLOSPON == 0)) %>% 
                                            filter(if_all(all_of(covs_names), ~ !is.na(.))) %>% 
                                            mutate(INCIDENT_RSCA = ifelse(INCIDENT_M13_RHEUMA == 1 | INCIDENT_SCTD == 1 | INCIDENT_M13_ANKYLOSPON == 1, 1, 0 )) %>% 
                                            mutate(RSCA_AGEDIFF = pmin(M13_RHEUMA_AGEDIFF, M13_ANKYLOSPON_AGEDIFF, SCTD_AGEDIFF))
col_data_rownames <- col_data_filtered %>% rownames()

# Subset tse object by filtered rownames  and update col data 
tse_subset <- tse[, col_data_rownames]
SummarizedExperiment::colData(tse_subset) <- S4Vectors::DataFrame(col_data_filtered)
# Agglomerate by Species 
tse_subset_sp <- agglomerateByRank(tse_subset, rank = "species")

```

# get numbers of excluded people
```{r}

col_data_filtered_1 <- col_data %>% filter(PROJECT == "FR02") 

col_data_no_anti <- col_data_filtered_1 %>% filter((BL_USE_RX_J01_1mo == 0))
col_data_no_anti_preg <- col_data_no_anti %>% filter(GRAVID == 1 | is.na(GRAVID))
col_data_no_anti_preg_totR <- col_data_no_anti_preg %>% filter(total_reads > 50000)
col_data_no_anti_preg_totR_misCov <- col_data_no_anti_preg_totR %>% filter(if_all(all_of(covs_names), ~ !is.na(.)))
col_data_no_anti_preg_totR_misCov_preval <- col_data_no_anti_preg_totR_misCov %>% filter((PREVAL_M13_RHEUMA == 0) & (PREVAL_SCTD == 0) & (PREVAL_M13_ANKYLOSPON == 0))
```


# Sample characteristics  
```{r}

# Fix and prepare data
col_data_all <- col_data_filtered %>% select(covs_names, INCIDENT_RSCA, RSCA_AGEDIFF)

  # Fix formatting of variables 
  col_data_all$CURR_SMOKE <- as.factor(col_data_all$CURR_SMOKE) 
  col_data_all$PREVAL_DIAB <- as.factor(col_data_all$PREVAL_DIAB)
  col_data_all$MEN <- as.factor(col_data_all$MEN)
  col_data_all$Q57X <- as.factor(col_data_all$Q57X)
  col_data_all$PREVAL_CVD <- as.factor(col_data_all$PREVAL_CVD)
  col_data_all$PREVAL_CR_ANYCANC <- as.factor(col_data_all$PREVAL_CR_ANYCANC)
  col_data_all$INCIDENT_RSCA <- as.factor(col_data_all$INCIDENT_RSCA)

col_data_no_rsca <- col_data_all %>% filter(INCIDENT_RSCA == 0)

col_data_rsca <- col_data_all %>% filter(INCIDENT_RSCA == 1)

# Create characteristics tables
Charc_table_all <- table1 (~ MEN + BL_AGE + BMI + Q57X + CURR_SMOKE + ALKI2_FR02 + PREVAL_DIAB + PREVAL_CVD + PREVAL_CR_ANYCANC + RSCA_AGEDIFF, data = col_data_all)
Charc_table_all
 
Charc_table_no_rsca <- table1 (~ MEN + BL_AGE + BMI + Q57X + CURR_SMOKE + ALKI2_FR02 +  PREVAL_DIAB + PREVAL_CVD + PREVAL_CR_ANYCANC + RSCA_AGEDIFF, data = col_data_no_rsca)
Charc_table_no_rsca

Charc_table_rsca <- table1 (~ MEN + BL_AGE + BMI + Q57X + CURR_SMOKE + ALKI2_FR02 +  PREVAL_DIAB + PREVAL_CVD + PREVAL_CR_ANYCANC + RSCA_AGEDIFF, data = col_data_rsca)
Charc_table_rsca

```

# Alpha diversity 
```{r}
# Get Shannon index
tse_subset_sp <- addAlpha(
  tse_subset_sp,
  assay.type = "counts",
  index = "shannon",
  name = "shannon"
)

# Convert colData to dataframe for cox model
col_data_subtse <- as.data.frame(colData(tse_subset_sp))

# Run Cox model for all covars 
full_formula <- as.formula(paste("Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ scale(shannon) +", covs_formula))

full_formula
    
cox_model_all_covars <- coxph(full_formula, data = col_data_subtse)
tidy_cox_all_covars <- broom::tidy(cox_model_all_covars, exponentiate = TRUE, conf.int = TRUE)
tidy_cox_all_covars
write_xlsx(tidy_cox_all_covars, "T1_shannon_covars_rhC.xlsx")

# Run Cox model for age and sex
cox_model_age_and_sex <- coxph(Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ scale(shannon) + BL_AGE + MEN, data = col_data_subtse)

tidy_cox_age_and_sex <- broom::tidy(cox_model_age_and_sex, exponentiate = TRUE, conf.int = TRUE)
tidy_cox_age_and_sex
write_xlsx(tidy_cox_age_and_sex, "T2_shannon_age_and_sex_rhC.xlsx")


```

```{r}
col_data_subtse_f$INCIDENT_RSCA <- as.factor(col_data_subtse_f$INCIDENT_RSCA)

m2 <- glm(INCIDENT_RSCA ~ scale(shannon),
          family = "binomial",
  data = col_data_subtse
  )
summary(m2)
exp(coef(m2))
model_H0 <- glm(INCIDENT_RSCA ~ 1, family = "binomial", data = col_data_subtse_f)
beta0 <- coef(model_H0)[1]
p_H0 <- plogis(beta0) 
p_H0


```



# Cox model for taxa analysis  
```{r}
# Taxa analysis 

# Subset by prevalence
tse_subset_sp_rl <- transformAssay(tse_subset_sp, assay.type = "counts", method = "relabundance")

tse_subset_pr <- subsetByPrevalentFeatures(tse_subset_sp_rl, rank = "species", assay.type = "relabundance", prevalence = 5/100, detection = 0.1/100)

# clr-transform counts
tse_subset_pr <- transformAssay(tse_subset_pr, assay.type = "counts", method = "clr", pseudocount = TRUE)

# Transpose and combine colData with assay
 tse_assay_clr <- as.data.frame(t(assay(tse_subset_pr, "clr")))
 combined_col_assay <- cbind(col_data_subtse, tse_assay_clr)
 
# Store species names
Species <- colnames(tse_assay_clr)
 
 
 # Run cox model for all covars 
 cox_taxa_covars_sp_rhC <- expand.grid(Species = Species) %>% 
   mutate(formula = glue::glue("Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ scale(`{Species}`) + {paste(names(covs_nicenames), collapse = ' + ')}")) %>%
   mutate(model= map(formula, ~ coxph(as.formula (.x), data=combined_col_assay))) %>%
   filter(!is.null(model)) %>% 
   mutate (tidy = map(model, ~ broom::tidy (.x, exponentiate = TRUE, conf.int = TRUE))) %>% 
   unnest (tidy) %>%
   filter (grepl("scale", term)) %>% 
   mutate (qvalue = p.adjust(p.value, method = "BH"))%>% 
   select (-model) %>% 
   arrange(qvalue)
 
 write_xlsx(cox_taxa_covars_sp_rhC, "T3_taxa_covars_sp_rhC.xlsx")
 
 # Run cox model for sex and age 
 cox_taxa_age_sex_sp_rhC <- expand.grid(Species = Species) %>% 
   mutate(formula = glue::glue("Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ scale(`{Species}`) + BL_AGE + MEN")) %>%
   mutate(model= map(formula, ~ coxph(as.formula (.x), data=combined_col_assay))) %>%
   filter(!is.null(model)) %>% 
   mutate (tidy = map(model, ~ broom::tidy (.x, exponentiate = TRUE, conf.int = TRUE))) %>% 
   unnest (tidy) %>%
   filter (grepl("scale", term)) %>% 
   mutate (qvalue = p.adjust(p.value, method = "BH"))%>% 
   select (-model) %>% 
   arrange(qvalue)
 
  write_xlsx(cox_taxa_age_sex_sp_rhC, "T4_taxa_age_sex_sp_rhC.xlsx")
 
 # Cox model for taxa (genus-level) analysis, all covars 
 
 # Subset by prevalence
 tse_subset_gn <- agglomerateByRank(tse_subset, rank = "genus")
 
 tse_subset_gn_rl <- transformAssay(tse_subset_gn, assay.type = "counts", method = "relabundance")
 
 tse_subset_pr_gn <- subsetByPrevalentFeatures(tse_subset_gn_rl, rank = "genus", assay.type = "relabundance", prevalence = 5/100, detection = 0.1/100)
 
 # clr-transform counts
 tse_subset_pr_gn <- transformAssay(tse_subset_pr_gn, assay.type = "counts", method = "clr", pseudocount = TRUE)
 
 # Transpose and combine colData with assay
 tse_assay_clr_gn <- as.data.frame(t(assay(tse_subset_pr_gn, "clr")))
 combined_col_assay_gn <- cbind(col_data_subtse, tse_assay_clr_gn)
 
 # Store Genus names
 Genus <- colnames(tse_assay_clr_gn)
 
 # Run cox model for all covars 
 cox_taxa_covars_gn_rhC <- expand.grid(Genus = Genus) %>% 
   mutate(formula = glue::glue("Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ scale(`{Genus}`) + {paste(names(covs_nicenames), collapse = ' + ')}")) %>%
   mutate(model= map(formula, ~ coxph(as.formula (.x), data=combined_col_assay_gn))) %>%
   filter(!is.null(model)) %>% 
   mutate (tidy = map(model, ~ broom::tidy (.x, exponentiate = TRUE, conf.int = TRUE))) %>% 
   unnest (tidy) %>%
   filter (grepl("scale", term)) %>% 
   mutate (qvalue = p.adjust(p.value, method = "BH"))%>% 
   select (-model) %>% 
   arrange(qvalue)
 
 write_xlsx(cox_taxa_covars_gn_rhC, "T5_taxa_covars_gn_rhC.xlsx")
 
 # Run model for age and sex only
 cox_taxa_age_sex_gn_rhC <- expand.grid(Genus = Genus) %>% 
 mutate(formula = glue::glue("Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ scale(`{Genus}`) + BL_AGE + MEN")) %>%
   mutate(model= map(formula, ~ coxph(as.formula (.x), data=combined_col_assay_gn))) %>%
   filter(!is.null(model)) %>% 
   mutate (tidy = map(model, ~ broom::tidy (.x, exponentiate = TRUE, conf.int = TRUE))) %>% 
   unnest (tidy) %>%
   filter (grepl("scale", term)) %>% 
   mutate (qvalue = p.adjust(p.value, method = "BH"))%>% 
   select (-model) %>% 
   arrange(qvalue)
 
 write_xlsx(cox_taxa_age_sex_gn_rhC, "T6_taxa_age_sex_gn_rhC.xlsx")

```


# Cox model for taxa with follow-up of 10 years only 
```{r}


# Limit follow-up to 10 yrs and change incidence after 10 yrs to 0
col_data_fw10 <- col_data_filtered %>% mutate(RSCA_AGEDIFF_FW10 = ifelse (RSCA_AGEDIFF > 10, 10, RSCA_AGEDIFF)) %>% mutate(INCIDENT_RSCA_FW10 = ifelse(RSCA_AGEDIFF > 10, 0, INCIDENT_RSCA ))

# Transpose and combine colData with assay
 tse_assay_clr <- as.data.frame(t(assay(tse_subset_pr, "clr")))
 combined_col_assay_fw10 <- cbind(col_data_fw10, tse_assay_clr)
 
# Store species names
Species <- colnames(tse_assay_clr)
 
 
 # Run cox model for all covars 
 cox_taxa_covars_sp_rhC_fw10 <- expand.grid(Species = Species) %>% 
   mutate(formula = glue::glue("Surv(RSCA_AGEDIFF_FW10, INCIDENT_RSCA_FW10) ~ scale(`{Species}`) + {paste(names(covs_nicenames), collapse = ' + ')}")) %>%
   mutate(model= map(formula, ~ coxph(as.formula (.x), data=combined_col_assay_fw10))) %>%
   filter(!is.null(model)) %>% 
   mutate (tidy = map(model, ~ broom::tidy (.x, exponentiate = TRUE, conf.int = TRUE))) %>% 
   unnest (tidy) %>%
   filter (grepl("scale", term)) %>% 
   mutate (qvalue = p.adjust(p.value, method = "BH"))%>% 
   select (-model) %>% 
   arrange(qvalue)
 
 write_xlsx(cox_taxa_covars_sp_rhC_fw10, "T11_taxa_covars_sp_rhC_fw10.xlsx")


```

# Figure 1 
```{r}
# Panel A
Permanova_rsca <- readRDS("~/Workspace/Autoim/rhC/Permanova_rsca.rds")
```

```{r}

sub_per <- Permanova_rsca [, 1:6242]
colData(sub_per)$INCIDENT_RSCA <- as.factor(colData(sub_per)$INCIDENT_RSCA)
RDA_plot <- plotRDA(sub_per, "RDA", colour.by = "INCIDENT_RSCA", add.ellipse = "color", ellipse.linewidth = 1) + scale_colour_discrete(
  breaks = c("1", "0"),
    labels = c("Yes", "No")) + labs(colour = "Incident ARD")+ theme(
  axis.title = element_text(size = 16),      # axis titles
  axis.text = element_text(size = 16),       # axis tick labels
  legend.text = element_text(size = 16), 
  legend.title = element_text(size = 16),
   legend.position = c(0.07, 0.9) # legend labels
)

# Panel B
# Create forest plot for significant species for all covar model

cox_covars_fltr <- cox_taxa_covars_sp_rhC %>% 
                   slice(1:10) %>% 
                   select(Species, estimate, std.error, conf.low, conf.high, qvalue) %>% 
                   rename("FDR" = qvalue) %>% 
                   mutate(std.error = round(std.error, 3), `FDR` = round(`FDR`, 3))

# Create HR (95% CI) column 
cox_covars_fltr$`HR (95% CI)` <- ifelse(is.na(cox_covars_fltr$estimate), "",
                             sprintf("%.2f (%.2f to %.2f)",
                                     cox_covars_fltr$estimate, cox_covars_fltr$conf.low, cox_covars_fltr$conf.high))

# Create an empty column for the forest plot to display CI.
cox_covars_fltr$` ` <- paste(rep(" ", 20), collapse = " ")

# Forest plot theme

tm <- forest_theme(base_size = 15,
                   ci_pch = 15,
                   ci_col = "black",
                   ci_fill = "black",
                   ci_alpha = 1,
                   ci_lty = 1,
                   ci_lwd = 1,
                   ci_Theight = 0.2,
                   core=list(bg_params=list(fill = c("grey97", "white"))))
                   
    
forest_plot_covars <- forest(cox_covars_fltr[, c(1, 7, 8, 6)],
            est = cox_covars_fltr$estimate,
            lower = cox_covars_fltr$conf.low, 
            upper = cox_covars_fltr$conf.high,
            sizes = 0.4,
            ci_column = 3, 
            ref_line = 1,
            xlim = c(0,2),
            x_trans  = "log",
            ticks_at = c(0.5, 0.75, 1, 1.5,2),
            theme = tm, 
            xlab = "Hazard ratio"
            )

forest_plot_covars <- edit_plot(forest_plot_covars, col = 1, gp = gpar(fontface = "italic"))

# Panel C
pathways_results <- readRDS("pathways.rds")

cox_covars_fltr_pw <- pathways_results %>% 
                   slice(1:10) %>% 
                   select(pathways, estimate, std.error, conf.low, conf.high, qvalue) %>% 
                   rename("FDR" = qvalue) %>% 
                   mutate(std.error = round(std.error, 3), `FDR` = round(`FDR`, 3))

# Create HR (95% CI) column 
cox_covars_fltr_pw$`HR (95% CI)` <- ifelse(is.na(cox_covars_fltr_pw$estimate), "",
                             sprintf("%.2f (%.2f to %.2f)",
                                     cox_covars_fltr_pw$estimate, cox_covars_fltr_pw$conf.low, cox_covars_fltr_pw$conf.high))

# Create an empty column for the forest plot to display CI.
cox_covars_fltr_pw$` ` <- paste(rep(" ", 20), collapse = " ")


# Clean pathways 

cox_covars_fltr_pw <- cox_covars_fltr_pw %>% rename(Pathways = pathways) 
cox_covars_fltr_pw$Pathways <- gsub(pattern = ".*PWY:", "", cox_covars_fltr_pw$Pathways)
# Forest plot 

  forest_plot_covars_pw <- forest(cox_covars_fltr_pw[, c(1, 7, 8, 6)],
            est = cox_covars_fltr_pw$estimate,
            lower = cox_covars_fltr_pw$conf.low, 
            upper = cox_covars_fltr_pw$conf.high,
            sizes = 0.4,
            ci_column = 3, 
            ref_line = 1,
            xlim = c(0,2),
            x_trans  = "log",
            ticks_at = c(0.5, 0.75, 1, 1.5,2),
            theme = tm, 
            xlab = "Hazard ratio"
            )
# Combine plots
layout_matrix <- rbind(c(1, 2),
                       c(1, 3))
RDA_plot <- arrangeGrob(RDA_plot, top = textGrob("a", x = unit(0, "npc"), just = "left", gp = gpar(fontsize = 16, fontface = "bold")))
forest_plot_covars <- arrangeGrob(forest_plot_covars, top = textGrob("b", x = unit(0, "npc"), just = "left", gp = gpar(fontsize = 16, fontface = "bold")))
forest_plot_covars_pw <- arrangeGrob(forest_plot_covars_pw, top = textGrob("c", x = unit(0, "npc"), just = "left", gp = gpar(fontsize = 16, fontface = "bold")))

Figure_ard <- grid.arrange(RDA_plot, forest_plot_covars, forest_plot_covars_pw,
                           
                           layout_matrix = layout_matrix)
ggsave("Figure_ard.png", Figure_ard, width = 20, height = 8, dpi = 350, bg = "white")

```

#Cox model results for covariates for top taxon
```{r}

full_formula_top <- as.formula(paste("Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ scale(`Scatocola faecipullorum`) +", covs_formula))

model_top <- coxph(full_formula_top, data = combined_col_assay)
tidy_cox_top <- broom::tidy(model_top, exponentiate = TRUE, conf.int = TRUE)
write_xlsx(tidy_cox_top, "T10_top_taxon_rhC.xlsx")

```


# Random Survival Forest (THIS TAKES TIME)
```{r}

# Function needed later
m_neat <- function(x, colnames = NULL) {
  x <- x %>%
    as.data.frame() %>% 
    rownames_to_column()
  
  if(!is.null(colnames)) {
    x <- x %>% set_colnames(colnames)
  }
  
  return(x)
}

Sp <- Species
# List of independent variable sets: core, covariates, both core and covariates
rf_predictor_sets <- list(core = Sp,
                          covariates = covs_names,
                          core_and_covariates = c(Sp, covs_names))
set.seed(178)
rf_all <- lapply(names(rf_predictor_sets), function(x) {
  print(x)
  
  rf <- rfsrc(Surv(RSCA_AGEDIFF, INCIDENT_RSCA) ~ .,
              data = combined_col_assay[, c("RSCA_AGEDIFF", "INCIDENT_RSCA", rf_predictor_sets[[x]])],
              importance = TRUE)
  
  return(rf)
}) %>% 
  set_names(names(rf_predictor_sets))

# Save raw results
saveRDS(rf_all, file = "survival_random_forest_raw_results_rhC.rds")

# Get c-statistics
all_harrell_c <- sapply(rf_all, function(x) 1 - x$err.rate[length(x$err.rate)])
all_harrell_c

  # Combine importances and independent variable sets in a table
rsf_table <- data.frame(feature = rf_predictor_sets[["core_and_covariates"]])

for(pred in names(rf_predictor_sets)) {
  
  df <- rf_all[[pred]]$importance %>%
    as.data.frame() %>% 
    m_neat(colnames = c("feature", pred)) %>% 
    arrange()
  
  rsf_table <- full_join(rsf_table, df, "feature")
  
}

# Arrange to descending order 
rsf_table <- rsf_table %>%
  arrange(desc(core_and_covariates)) %>% 
  set_colnames(c("Feature", "Microbiome", "Covariates", "Microbiome and Covariates"))

writexl::write_xlsx(rsf_table, "T7_random_survival_rhC.xlsx")


# Sup. Figure 1 , plot the top 20 taxa with highest imp scores

# Clean table 
#rsf_table_plot <- rsf_table %>% 
  #select(`Microbiome and Covariates`, Feature) %>% filter(!grepl("BL_AGE|MEN|BMI|CURR_SMOKE|ALKI2_FR02|Q57X|PREVAL_DIAB|PREVAL_CVD|PREVAL_CR_ANYCANC", Feature)) %>% 
  #arrange(desc(`Microbiome and Covariates`)) %>% 
  #rename(Species = Feature, `Importance score` = `Microbiome and Covariates`)

#rsf_table_plot <- rsf_table_plot[1:20, ] # Select top 20 
#rsf_table_plot <- rsf_table_plot %>%  mutate(Species=factor(Species, levels=Species))

#importance_plot <- ggplot(rsf_table_plot, aes(x = Species, y = `Importance score`)) + geom_col(width = 0.8, fill ="steelblue4") + labs(x=NULL)+ theme(
                   
                   #panel.border = element_blank(),
                   #axis.line.x = element_line(colour = "black"),
                   #axis.line.y = element_line(colour = "black"),
                   #axis.text.x = element_text(angle=45, hjust=1, size = 17),
                   #axis.text.y = element_text(size = 17),
                   #axis.title.y = element_text(size = 17),
                   #panel.background = element_rect(fill = "white", colour = "white"),
                   #plot.background = element_rect(fill = "white", colour = "white"),
                    #aspect.ratio = 1)

#ggsave("Figure1S_rhC.png", plot = importance_plot, width = 9.2, height = 10, units = "in", dpi = 350)

```




